app_version: 0.1.7b
app_resource_path: $RESOURCE_PATH
http_services:
  worker:
    service_base_path: $RESOURCE_PATH
  artifacts_server:
    port: 4243
    path: /bucket
    runtime_base_path: $RESOURCE_PATH/locker
concurrent_pool:
  max_concurrent_tasks: 2